version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fraud_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fraud_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: fraud_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: