"""add new transaction fields

Revision ID: 0e39b1a3d5ac
Revises: 821e0ddda62a
Create Date: 2026-04-01 13:14:17.891733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e39b1a3d5ac'
down_revision: Union[str, Sequence[str], None] = '821e0ddda62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('tx_type', sa.String(), nullable=False),
    sa.Column('merchant_category', sa.Integer(), nullable=False),
    sa.Column('device_used', sa.String(), nullable=True),
    sa.Column('payment_channel', sa.String(), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=True),
    sa.Column('fraud_risk', sa.Integer(), nullable=True),
    sa.Column('fraud_label', sa.String(), nullable=True),
    sa.Column('fraud_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_fraud_risk'), 'transactions', ['fraud_risk'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_is_fraud'), 'transactions', ['is_fraud'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_is_fraud'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fraud_risk'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
