"""add merchant/device/payment fields

Revision ID: 821e0ddda62a
Revises: bfdb6223cbbb
Create Date: 2026-03-31 11:02:19.144322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821e0ddda62a'
down_revision: Union[str, Sequence[str], None] = 'bfdb6223cbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_type', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('merchant_category', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('device_used', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_channel', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('fraud_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'fraud_reason')
    op.drop_column('transactions', 'payment_channel')
    op.drop_column('transactions', 'device_used')
    op.drop_column('transactions', 'merchant_category')
    op.drop_column('transactions', 'tx_type')
    # ### end Alembic commands ###
